events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=30s;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      set $api_url http://api:8080;
      proxy_pass $api_url;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Api-Key $http_x_api_key;
    }

    location /health {
      set $health_url http://api:8080/health;
      proxy_pass $health_url;
      proxy_set_header Host $host;
      proxy_set_header X-Api-Key $http_x_api_key;
    }
  }
}
